name: pws
channels:
  - conda-forge
  - nodefaults
dependencies:
  - asv
  - cartopy
  - click != 8.1.0
  - dataretrieval
  - contextily
  - epiweeks4cf
  - filelock
  - folium
  - geopandas
  - geoviews
  - gfortran>=15.2.0
  - git
  - make
  - holoviews<=1.20.0
  - hvplot
  - ipython
  - ipywidgets
  - jupyter>=1.1.1
  - jupyter-black
  - jupyterlab>=4.5.5
  - nbdime
  - nbconvert
  - netCDF4
  - networkx
  - numpy>=2.0.0
  - numba
  - pandas>=1.4.0
  - pint
  - pip
  - pre-commit
  - pydot
  - pytest!=8.1.0
  - pytest-cov
  - pytest-env
  - pytest-order
  - pytest-xdist
  - python=3.13
  - pyyaml
  - pyvis
  - ruff
  - safety
  - shapely
  - sphinx
  - sphinx-book-theme>=0.3.3
  - sphinx-autodoc-typehints>=2.2.1
  - sphinx-autosummary-accessors
  - sphinx-copybutton
  - tqdm
  - xarray>=2024.06.0
  - xmltodict
  - zarr
  - pip:
      - git+https://github.com/jararias/mpsplines.git
      - pyPRMS>=0.10.0
      - modflow-devtools[dfn]==1.7.0
      - pytest-error-for-skips
      - "flopy[codegen] @ git+https://github.com/modflowpy/flopy.git"
