name: pws
channels:
  - conda-forge
  - nodefaults
dependencies:
  - asv
  - cartopy
  - click != 8.1.0
  - dataretrieval
  - contextily
  - epiweeks4cf
  - filelock
  - flopy
  - folium
  - geopandas
  - geoviews
  - git
  - holoviews<=1.20.0
  - hvplot
  - ipython
  - modflowapi
  - netCDF4
  - networkx
  - numpy>=2.0.0
  - numba
  - pandas>=1.4.0
  - pint
  - pip
  - pre-commit
  - pydot
  - pytest!=8.1.0
  - pytest-cov
  - pytest-env
  - pytest-order
  - pytest-xdist
  - python<3.12,>=3.10
  - pyyaml
  - rasterstats
  - ruff
  - shapely
  - sphinx
  - sphinx-book-theme>=0.3.3
  - sphinx-autodoc-typehints>=2.2.1
  - sphinx-autosummary-accessors
  - sphinx-copybutton
  - tqdm
  - xarray>=2024.06.0
  - xmltodict
  - pip:
      - asv
      - git+https://github.com/modflowpy/flopy.git
      - modflow-devtools[dfn] @ git+https://github.com/MODFLOW-ORG/modflow-devtools.git
      - git+https://github.com/jararias/mpsplines.git
      - git+https://github.com/jlarsen-usgs/dany.git
      - git+https://github.com/pygsflow/pygsflow.git@develop
      - pyPRMS==0.9.7
      - sphinx-autodoc-typehints>=2.2.1
