[pytest]
addopts = --order-dependencies
filterwarnings =
    ignore:.*is not an available control option:UserWarning:pywatershed.base.control
python_files =
    test_*.py
python_functions =
    make_*
    test_*
